name: "Check clang format"

inputs:
  path:
    description: 'Path to source code'
    default: "."

runs:
  using: composite
  steps:
    - name: "Check clang format"
      working-directory: ${{ inputs.path }}
      run: |
        pwd
        ls
        ${GITHUB_ACTION_PATH}/check-clang-format.sh
      shell: bash
